# Generated by Django 5.1.7 on 2025-03-31 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='covert_page',
            field=models.ImageField(upload_to='books_covert/'),
        ),
    ]
