services:
  - type: web
    name: kama-blog
    env: python
    buildCommand: ./build.sh
    startCommand: cd myblog && gunicorn myblog.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: kama-blog.onrender.com 
      - key: DATABASE_URL
        fromDatabase:
          name: kama-blog-db
          property: connectionString

databases:
  - name: kama-blog-db
    databaseName: kama_blog_db
    user: kama_blog_user
